theme: jekyll-theme-minimal
title: 'UC Davis Bioinformatics Workshop Base Template'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Intro to the Workshop and Core
    url: welcome
  - title: Examples of Markdown Formatting
    url: examples


  - heading: Snakemake
  - title: Introduction
    url: snakemake/snakemake_intro
  - title: RNAseq/TagSeq Workflow
    url: snakemake/rna_tag_sm

